[package]
name = "use-php-ini"
description = "PHP INI metadata primitives for RustUse."
publish = true
authors.workspace = true
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
readme = "README.md"
documentation = "https://docs.rs/use-php-ini"
keywords = ["php", "ini", "config"]
categories = ["config", "development-tools"]

[lints]
workspace = true
